### ISSUE TITLE
Curious about the choice "GPL v3.0" license when more permissive licensing options might have been avaiable

### ISSUE THREAD

**Issue by Mechazo11** [jeremysalwen/ORB_SLAM_COMMUNITY#1] opened 2024-08-09 18:37 UTC
Dear Contributors and Users. 

ORB-SLAM3 from its inception, has always been "GPL v3.0". 

While this license has promoted its widespread usage in academia and in a number of open source projects (if I am not mistaken), recent state-of-the-art robotics frameworks such as Space ROS created with "Apache 2.0" or "MIT" licenses prevents its integration due to licensing restriction imposed by GPL v3.0. 

As an example, a discussion on GPL v3.0's limited compatibility with Apache 2.0 can be found [here](https://opensource.stackexchange.com/questions/11082/why-is-the-gnu-gpl-v3-compatible-with-the-apache-license-v2-0/11319#11319)  

Hence, I opened this issue in hopes to start a discussion on the benefits / disadvantages of changing the license for "ORB-SLAM3" from ```GPL v3.0```.

With best regards,
@Mechazo11

**Comment by jeremysalwen** [comment] 2024-08-11 01:45
Hi @Mechazo11,

Two things,

First, ORB_SLAM was released by its original authors as GPLv3.  The community has no choice but to comply.  They do provide commercial licenses, but you have to pay for that.

Second, the Apache license, MIT license, BSD license, etc, all allow you to integrate GPL code.  HOWEVER, the combined code must be under the GPL.  This is fine, since the GPL just requires you to release the source code, which hopefully you would be doing anyways :)   If we were to make a module for Space ROS, that would be fine, the module would just be released as GPL.

Jeremy

**Comment by Mechazo11** [comment] 2024-08-11 02:57
Hi @jeremysalwen 

Thank you very much for the clarification. The fact that the new codebase had to be in GPL was new to me.

I recently had a conversation about this issue with a few core maintainers of Space ROS. According to them, since Space ROS is in Apache 2.0 license, they stated, ORB SLAM 3 could not be integrated with Space ROS since all their code base are in Apache 2.0 / MIT licenses and thus, ORB SLAM 3 would not play well with them. 

On a different note, @jeremysalwen I wanted to reach out to you over email. Where may I find your email address?

**Comment by jeremysalwen** [comment] 2024-08-11 04:47
So the problem is that they probably have some users who do not wish to release their source code.  If they were to incorporate ORB_SLAM, then the combined software would be under the GPLv3, and any users would be required to release their source code to anyone they shared their binary with.

**Closed as completed** 2024-08-15 18:26 UTC
Labels: enhancement, question
